Added RouteAcquisition File & Downloaded all Data
sustainableaviation/demandmap pull request #20
Opened 2024-04-30 09:33 UTC by dodedic

Iterates over all airports and months of the year, data stored on Sharepoint.
Added .env to .gitignore file.

@michaelweinold for some reason I can't access they key from the .env file, am still working on it.

2024-04-30 09:48 UTC, dodedic commented
@michaelweinold both older commits 30f20ee and ca8a3c8 contain sensitive data from a week ago, we need to remove those first.

2024-04-30 09:50 UTC, michaelweinold commented
> we need to remove those first.

Be my guest 😎

2024-04-30 10:46 UTC, michaelweinold commented
> I now just simply reset the compromised API key

![hacker-hackerman](https://github.com/sustainableaviation/demandmap/assets/23102087/ac9488f3-4211-44d2-83f6-7825307bcbaa)

2024-04-30 10:56 UTC, michaelweinold requested changes
Nice work - see my comments.

2024-04-30 10:56 UTC, michaelweinold commented on ADB/Airport Data/RouteAcquisition.py
> +from dotenv import load_dotenv
I would recommend we use native Python functionality instead. [TOML support is relatively new](https://realpython.com/python-toml/). You can take some inspiration from: https://github.com/sustainableaviation/EcoPyLot/blob/8a6b7b5dff270293a38754459cb5f2812471245e/ecopylot/utils.py#L6

2024-04-30 10:56 UTC, michaelweinold commented on ADB/Airport Data/RouteAcquisition.py
> +# Function to retrieve data from the API for a given airport ICAO code and date
All fine for a draft PR. When we go to production, I suggest we follow [the NumPy docstrings style guide](https://numpydoc.readthedocs.io/en/latest/format.html).

2024-04-30 10:56 UTC, michaelweinold commented on ADB/Healtcheck.py
This could later be moved to a single function - with some docstring documentation.

2024-04-30 10:56 UTC, michaelweinold commented on ADB/RouteAcquisition - Kopie.py
Is this file an undesired copy?

2024-05-10 10:41 UTC, dodedic commented
@michaelweinold Changes implemented as per comments.

2024-05-12 08:43 UTC, michaelweinold commented
...some more work needed, @dodedic.

2024-05-13 14:50 UTC, dodedic commented
I cannot see any new comments though @michaelweinold

2024-05-13 15:04 UTC, michaelweinold requested changes
...can you see my comments now?

2024-05-13 17:50 UTC, dodedic commented
All done! @michaelweinold 
Also added the config.toml file template now as well and changed the .gitignore back to ignore it!

2024-05-14 09:07 UTC, michaelweinold commented on ADB/AirportData/RouteAcquisition.py
> +import toml
Excellent - just native imports!

2024-05-14 09:07 UTC, michaelweinold commented on ADB/AirportData/config.toml
> +key = "API_KEY_HERE"
Nice, nice, nice!

2024-05-14 09:09 UTC, michaelweinold commented on ADB/Healtcheck.py
> +def get_api_key():
As I mentioned earlier (https://github.com/sustainableaviation/demandmap/pull/20#discussion_r1584561530), this is all fine for now. Before we release the code, you will need to add Numpy-style doctrings.

2024-05-14 09:10 UTC, merged