World map plotting
sustainableaviation/demandmap pull request #29
Opened 2024-05-14 15:31 UTC by arebe337

2024-05-14 21:43 UTC, arebe337 commented
@michaelweinold did all the adjustments and should be ready for review again

2024-05-14 23:51 UTC, michaelweinold requested changes
...one file needs to be removed, otherwise this looks good.

2024-05-14 23:51 UTC, michaelweinold commented on ADB/__pycache__/data_transformation_pandas.cpython-312.pyc
`.pyc` files need to be added to the `.gitignore`.

2024-05-14 23:51 UTC, michaelweinold commented on ADB/Air_Traffic_Worldmap_year.pdf
Cool!

2024-05-15 07:21 UTC, arebe337 commented
Corrected all comments @michaelweinold

2024-05-15 09:40 UTC, merged