Data Added from literature
sustainableaviation/demandmap pull request #5
Opened 2024-03-16 09:02 UTC by dodedic

Added data from several sources.
Pyhton script updated to include said sources

2024-03-18 12:56 UTC, michaelweinold commented
@dodedic, I saw that my review comments had not been addressed. Please ping me when your PR is actually ready for re-review. Thanks 🫡

2024-03-18 13:05 UTC, dodedic commented
@michaelweinold, do you mean the comments from last Wednesday in Ben's latest message [here](https://github.com/sustainableaviation/demandmap/issues/2)?
Or is there a review tab on this PR that I cannot seem to find right now?

2024-03-18 13:31 UTC, dodedic commented
For me it's not showing any review conversation nor comments on the previous commit (from two days ago). If I'm looking in the wrong place please let me know because I am slightly baffled right now.

![image](https://github.com/sustainableaviation/demandmap/assets/118805682/45ede01d-2c51-45aa-83d2-8887f8349010)

2024-03-18 13:41 UTC, michaelweinold requested changes
...ok, maybe you'll see my comments now.

2024-03-18 13:47 UTC, michaelweinold commented on figures/forecasts_literature/forecasts_literature.py
> +    label='Airbus'
...add forecast years to all labels, please.

2024-03-19 08:34 UTC, michaelweinold commented
Thank you for integrating my comments. You can go back to the Flake8 formatting for function calls - and then I'll merge the PR.

2024-03-20 17:11 UTC, dodedic commented
- Colorblind-friendly colours added from [these suggestions](https://gist.github.com/thriveth/8560036)
- Position/size of legend adjusted
- Axis renamed
- ATI weird datapoint removed and replaced by calculated value with growth rate from literature

I am currently still struggling with the implementation of the vertical line at 2024 using plt.axvline (line 253). Maybe you could have a quick look at that and point out what I'm doing wrong. I need to rush off to work now since I'm working overnight so I thought I'd commit what I have already done so far.

2024-03-21 05:09 UTC, merged